Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DentalCenter.Models;
using Microsoft.AspNetCore.Authorization;

namespace DentalCenter.Controllers
{
    public class ContactsController : Controller
    {
        private readonly DentalCenterDBContext _context;

        public ContactsController(DentalCenterDBContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "admin")]
        // GET: Contacts
        public IActionResult Index()
        {
            List<ContactViewModel> contacts = new List<ContactViewModel>();
            var items = _context.Contact.ToList();
            foreach (var item in items)
            {
                contacts.Add(new ContactViewModel
                {
                    ContactId = item.ContactId,
                    ContactSurname= item.ContactSurname,
                    ContactName= item.ContactName,
                    ContactPhone  = item.ContactPhone,
                    ContactMessage = item.ContactMessage,
                });
            }
            return View(contacts);
        }


        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Contact == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact
                .FirstOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ContactId,ContactName,ContactSurname,ContactPhone,ContactMessage")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contact);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        [Authorize(Roles = "admin")]
        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Contact == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact.FindAsync(id);
            if (contact == null)
            {
                return NotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContactId,ContactName,ContactSurname,ContactPhone,ContactMessage")] Contact contact)
        {
            if (id != contact.ContactId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contact);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactExists(contact.ContactId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        [Authorize(Roles = "admin")]
        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Contact == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact
                .FirstOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Contact == null)
            {
                return Problem("Entity set 'DentalCenterDBContext.Contact'  is null.");
            }
            var contact = await _context.Contact.FindAsync(id);
            if (contact != null)
            {
                _context.Contact.Remove(contact);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteContact(List<ContactViewModel> cont) { 
            List<Contact> contacts = new List<Contact>();
            foreach (var item in cont)
            {
                if (item.Emps.Selected)
                {
                    var selectedContact = _context.Contact.Find(item.ContactId);
                    contacts.Add(selectedContact);
                }
            }
            _context.Contact.RemoveRange(contacts);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        private bool ContactExists(int id)
        {
          return (_context.Contact?.Any(e => e.ContactId == id)).GetValueOrDefault();
        }
    }
}

Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DentalCenter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using DentalCenter.Areas.Identity.Data;
using System.Numerics;
using Microsoft.IdentityModel.Tokens;

namespace DentalCenter.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly DentalCenterDBContext _context;
        private readonly IWebHostEnvironment _appEnvironment;
        private readonly UserManager<DentalCenterUser> _userManager;


        public DoctorsController(DentalCenterDBContext context, IWebHostEnvironment appEnvironment, UserManager<DentalCenterUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }

        // GET: Doctors
        public async Task<IActionResult> Index()
        {
              return _context.Doctors != null ? 
                          View(await _context.Doctors.ToListAsync()) :
                          Problem("Entity set 'DentalCenterDBContext.Doctors'  is null.");
        }

        
        // GET: Doctors/Details/5
        public async Task<IActionResult> Details(int? id)
        {


            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }
            var doctor = await _context.Doctors
                .FirstOrDefaultAsync(m => m.DoctorId == id);
            if (doctor == null)
            {
                return NotFound();
            }

            if (!doctor.DoctorPhoto.IsNullOrEmpty())
            {
                byte[] photodata = System.IO.File.ReadAllBytes(_appEnvironment.WebRootPath + doctor.DoctorPhoto);

                ViewBag.Photodata = photodata;
            }
            else
            {
                ViewBag.Photodata = null;
            }

            return View(doctor);
        }

        [Authorize(Roles = "admin, doctor")]
        // GET: Doctors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DoctorId,Email,DoctorSurname,DoctorName,DoctorPatronymic,DoctorSpecialization,DoctorCabinet,DoctorPhoto")] Doctor doctor, IFormFile? upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    string path = "/PhotoDoctors/" + upload.FileName;
                    using (var fileStream = new
                    FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await upload.CopyToAsync(fileStream);
                    }
                    doctor.DoctorPhoto = path;
                }

                _context.Add(doctor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors.Include(d => d.IdentityUser).Where(d => d.DoctorId == id).FirstOrDefaultAsync();
            if (doctor == null)
            {
                return NotFound();
            }

            if (!doctor.DoctorPhoto.IsNullOrEmpty())
            {
                byte[] photodata = System.IO.File.ReadAllBytes(_appEnvironment.WebRootPath + doctor.DoctorPhoto);
                ViewBag.Photodata = photodata;
            }
            else
            {
                ViewBag.Photodata = null;
            }

            return View(doctor);
        }

        [Authorize(Roles = "admin, doctor")]
        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DoctorId,Email,DoctorSurname,DoctorName,DoctorPatronymic,DoctorSpecialization,DoctorCabinet, IdentityUserId")] Doctor doctor, IFormFile? upload)
        {
            if (id != doctor.DoctorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    string path = "/PhotoDoctors/" + upload.FileName;
                    using (var fileStream = new
                    FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await upload.CopyToAsync(fileStream);
                    }
                    if (!doctor.DoctorPhoto.IsNullOrEmpty())
                    {
                        System.IO.File.Delete(_appEnvironment.WebRootPath +
                       doctor.DoctorPhoto);
                    }
                    doctor.DoctorPhoto = path;
                }

                try
                {
                    _context.Update(doctor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorExists(doctor.DoctorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        [Authorize(Roles = "admin, doctor")]
        // GET: Doctors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
                .FirstOrDefaultAsync(m => m.DoctorId == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Doctors == null)
            {
                return Problem("Entity set 'DentalCenterDBContext.Doctors'  is null.");
            }
            var doctor = await _context.Doctors.FindAsync(id);
            if (doctor != null)
            {
                _context.Doctors.Remove(doctor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoctorExists(int id)
        {
          return (_context.Doctors?.Any(e => e.DoctorId == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DentalCenter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/DentalCenter.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-view flex-grow-1">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img class="navbar-brand--img" asp-area="" src="~/img/logotype.svg" />
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1"> 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Услуги</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="Index">Врачи</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Create">Контакты</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">Список приемов</a>
                            </li>
                        </ul>
                    </div>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial"></partial>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="footer-view">
               <div class="footer-columns">
                    <div class="footer-first--column">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <img class="navbar-brand--img" asp-area="" src="~/img/logotype-footer.svg" />
                        </a>
                        <h6 class="footer-logotype-desc">
                            Dentalist - это местная клиника косметической, профилактической и <br> восстановительной стоматологии с самым высоким рейтингом на First Hill
                        </h6>
                        <div class="footer-follow-soc">
                            <p>Подпишись на нас</p>
                            <div class="footer-follow-soc--img soc-img">
                                <img src="/img/facebook.svg" class="soc-img--view" onclick="window.open('https://www.facebook.com')" />
                                <img src="/img/twitter.svg" class="soc-img--view" onclick="window.open('https://www.twitter.com')" />
                                <img src="/img/instagram.svg" class="soc-img--view" onclick="window.open('https://www.youtube.com')" />
                            </div>
                        </div>
                    </div>
                    <div class="footer-second--column second-column">
                        <p class="second-column--title footer-column--title">Быстрые ссылки</p>
                        <nav>
                            <ul class="navbar-nav-footer"> 
                                <li class="nav-item-footer">
                                    <a class="nav-link--footer" asp-area="" asp-controller="Services" asp-action="Index">Услуги</a>
                                </li>
                                <li class="nav-item-footer">
                                    <a class="nav-link--footer" asp-area="" asp-controller="Doctors" asp-action="Index">Доктора</a>
                                </li>
                                <li class="nav-item-footer">
                                    <a class="nav-link--footer" asp-area="" asp-controller="Contacts" asp-action="Create">Контакты</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="footer-third--column third-column">
                        <p class=" third-column--title footer-column--title"> Контакты и информация </p>
                        <div class="footer-navigate">
                            <div class="third-column--phone phone">
                                <img src="~/img/phone.svg" class="third-column-svg" />
                                <div class="phone-div">
                                    <p class="third-column-subtitle">Номер телефона</p>
                                    <a class="third-column--link" href="tel:89307414141"> 8 (930) 741 41 41 </a>
                                </div>
                            </div>
                            <div class="third-column--hour hour">
                                <img src="~/img/hour.svg" class="third-column-svg" />
                                <div class="hour-div">
                                    <p class="third-column-subtitle">Время работы</p>
                                    <p class="third-column--link">09:00 - 18:00</p>
                                </div>
                            </div>
                            <div class="third-column--map map">
                                <img src="~/img/map.svg" class="third-column-svg" />
                                <div class="map-div">
                                    <p class="third-column-subtitle">Наш адрес</p>
                                    <a class="map-link third-column--link" onclick="window.open('https://yandex.ru/maps/10668/murom/?ll=42.060994%2C55.552441&mode=poi&poi%5Bpoint%5D=42.060458%2C55.551434&poi%5Buri%5D=ymapsbm1%3A%2F%2Forg%3Foid%3D5776007362&z=17.96')">г.Муром, ул. Орлосвкая, д. 25Б.</a>
                                </div>
                            </div>
                        </div>
                    </div>
               </div>
               <div class="footer-privacy">
                    &copy; Dentalist. All Right Reserved -  <a asp-area="" class="footer-privacy" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
               </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/jquery.maskedinput.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>