Controllers/MakeAppoinmentsController.cs
using DentalCenter.Areas.Identity.Data;
using DentalCenter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;

namespace DentalCenter.Controllers
{
    [Authorize]
    public class MakeAppoinmentsController : Controller
    {
        private readonly DentalCenterDBContext _context;
        private readonly UserManager<DentalCenterUser> _userManager;

        public MakeAppoinmentsController(DentalCenterDBContext context, UserManager<DentalCenterUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> SelectService()
        {
            
            return View(await _context.Service.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> SelectService(int serviceId)
        {
            Service service = await _context.Service.Where(d => d.ServiceId == serviceId).FirstOrDefaultAsync();
            if (service == null)
            {
                return NotFound();
            }
            ViewBag.ServiceId = serviceId;
            
            return View(nameof(SelectDoctor), await _context.Doctors.Where(d => d.Services.Contains(service)).ToListAsync());
        }

        public async Task<IActionResult> SelectDoctor()
        {
            
            return View(await _context.Doctors.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> SelectDoctor(int serviceId, int doctorId)
        {
            Doctor doctor = await _context.Doctors.FindAsync(doctorId);
            Service service = await _context.Service.FindAsync(serviceId);
           
            if (doctor == null || service == null)
            {
                return NotFound();
            }
            ViewBag.ServiceId = serviceId;
            ViewBag.DoctorId = doctorId;
            return View(nameof(ChooseDate), await _context.Appointment.ToListAsync());
        }

        public async Task<IActionResult> ChooseDate()
        {
            return View(await _context.Appointment.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> ChooseDate(int serviceId, int doctorId, DateTime appointmentDateVisiting)
        {
            if (User.IsInRole("client"))
            {
                Client currentClient = await _context.Clients.FirstOrDefaultAsync(e => e.DentalCenterUserId == _userManager.GetUserId(HttpContext.User));

                ViewBag.Id = currentClient.Id;
            }

            var appointments = await _context.Appointment.ToListAsync();
            if (appointments == null)
            {
                return NotFound();
            }
            Doctor doctor = _context.Doctors.FirstOrDefault(d => d.DoctorId == doctorId);
            Service service = _context.Service.FirstOrDefault(d => d.ServiceId == serviceId);
            ViewBag.Doctor = doctor;
            ViewBag.Service = service;
            ViewBag.AppointmentDateVisiting = appointmentDateVisiting.ToShortDateString();
            if (appointments.Count(v => v.ServiceId == serviceId && v.DoctorId == doctorId && v.AppointmentDateVisiting == appointmentDateVisiting) > 0) { return View(appointments); }

            return View(nameof(ConfirmRecord));
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmRecord([Bind("ServiceId,DoctorId,AppointmentDateVisiting")] Appointment appointments)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appointments);
                await _context.SaveChangesAsync();
            }
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "Id", "FirstName", appointments.DoctorId);
            ViewData["ServiceId"] = new SelectList(_context.Service, "Id", "FirstName", appointments.ServiceId);
            ViewData["AppointmentDateVisiting"] = new SelectList(_context.Appointment, "Id", "FirstName", appointments.AppointmentDateVisiting);

            return RedirectToAction(nameof(Index), "Home");
        }
    }
}

Views/MakeAppoinments/ChooseDate.cshtml
@model IEnumerable<DentalCenter.Models.Appointment>

<main role="main" class="pb-3">
    <div class="contact-img appointments-make"></div>
    <div class="container">
        <h1 class="title">Выбор визита</h1>
        <div class="delete-view">
            @using (Html.BeginForm("ChooseDate", "MakeAppoinments", FormMethod.Post))
            {
                <div class="choosedate-view">
                    <input type="hidden" name="ServiceId" value="@ViewBag.ServiceId" />
                    <input type="hidden" name="DoctorId" value="@ViewBag.DoctorId" />
                    <label class="card-title">Дата визита</label>
                    <input type="date" name="AppointmentDateVisiting" class="form-control" />
                    <input type="submit" value="Выбрать" class="btn btn-primary btn-choosedate" />
                </div>
            }
        </div>
        <h3 class="title">Существующие записи</h3>
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.AppointmentDateVisiting)
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    @if (item.ServiceId == ViewBag.ServiceId && item.DoctorId == ViewBag.DoctorId)
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.AppointmentDateVisiting)
                        </td>
                    }
                </tr>
            }
        </table>
    </div>
</main>

Views/MakeAppoinments/ConfirmRecord.cshtml
@model DentalCenter.Models.Appointment


<main role="main" class="pb-3">
    <div class="contact-img confirm"></div>
    <div class="container">
        <h1 class="title">Подтверждение записи</h1>

        <div class="delete-view">
            @using (Html.BeginForm("ConfirmRecord", "MakeAppoinments", FormMethod.Post))
            {
            <div class="form-group">
                    <label class=""> <span>Услуга: </span> @ViewBag.Service.ServiceName</label>
                    <label class=""> <span>Цена:</span> @ViewBag.Service.ServicePrice</label>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Доктор: @ViewBag.Doctor.DoctorSurname  @ViewBag.Doctor.DoctorName @ViewBag.Doctor.DoctorPatronymic</label> 
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Дата встречи: @ViewBag.AppointmentDateVisiting</label>
                </div>

                <input type="hidden" asp-for="ServiceId" value="@ViewBag.Service.ServiceId" />
                <input type="hidden" asp-for="Id" value="@ViewBag.Id" />
                <input type="hidden" asp-for="DoctorId" value="@ViewBag.Doctor.DoctorId" />
                <input type="hidden" asp-for="AppointmentId" value="@ViewBag.AppointmentDateVisiting" />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Подтвердить" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>
</main>

Views/MakeAppoinments/SelectDoctor.cshtml
@model IEnumerable<DentalCenter.Models.Doctor>


<main role="main" class="pb-3">
    <div class="container">
        <h1 class="title">Выбор врача</h1>
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DoctorSurname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DoctorName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DoctorPatronymic )
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DoctorSpecialization)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DoctorCabinet)
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DoctorSurname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DoctorName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DoctorPatronymic)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DoctorSpecialization)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DoctorCabinet)
                    </td>
                    <td>
                        @using (Html.BeginForm("SelectDoctor", "MakeAppoinments", FormMethod.Post))
                        {
                            <div>
                                <input type="hidden" name="ServiceId" value="@ViewBag.ServiceId" />
                                <input type="hidden" name="DoctorId" value="@item.DoctorId" />
                                <input type="submit" value="Выбрать" class="btn btn-primary" />
                            </div>
                        }
                    </td>
                </tr>

            }
        </table>
    </div>
</main>

Views/MakeAppoinments/SelectService.cshtml
@model IEnumerable<DentalCenter.Models.Service>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main role="main" class="pb-3">
    <div class="container">
        <h1 class="title">Выбор услуги</h1>
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ServiceName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ServiceDecription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ServicePrice)
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ServiceName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ServiceDecription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ServicePrice)
                    </td>
                    <td>
                        @using (Html.BeginForm("SelectService", "MakeAppoinments", FormMethod.Post))
                        {
                            <div>
                                <input type="hidden" name="ServiceId" value="@item.ServiceId" />

                                <input type="submit" value="Выбрать" class="btn btn-primary" />
                            </div>
                        }
                    </td>
                </tr>

            }
        </table>
    </div>
</main>